CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255),
  email VARCHAR(512) UNIQUE
);

CREATE TABLE IF NOT EXISTS locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  latitude DECIMAL(10, 8),
  longitude DECIMAL(11, 8)
);

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    views INT,
    category_id BIGINT REFERENCES categories(id) NOT NULL,
    confirmed_requests INT,
    created_on VARCHAR(19),
    description VARCHAR(1000),
    event_date VARCHAR(19),
    initiator_id BIGINT REFERENCES users(id) NOT NULL,
    location_id BIGINT REFERENCES locations(id),
    paid BOOLEAN,
    published_on VARCHAR(19),
    request_moderation BOOLEAN,
    state VARCHAR(50)
);